// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApqK4PE69cNBYvSfoTkndbLAUC4wBtYaw',
    appId: '1:502668603925:android:9965decf38bddebc36541c',
    messagingSenderId: '502668603925',
    projectId: 'tik-tok-ee83a',
    databaseURL: 'https://tik-tok-ee83a-default-rtdb.firebaseio.com',
    storageBucket: 'tik-tok-ee83a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0z2G88HIlJ-O6l0QbKUSO5RMDsOk3Mw4',
    appId: '1:502668603925:ios:63e57d0af213a94c36541c',
    messagingSenderId: '502668603925',
    projectId: 'tik-tok-ee83a',
    databaseURL: 'https://tik-tok-ee83a-default-rtdb.firebaseio.com',
    storageBucket: 'tik-tok-ee83a.appspot.com',
    androidClientId: '502668603925-a1vhl0urepuetjieqob13ig7ccdmscal.apps.googleusercontent.com',
    iosClientId: '502668603925-qob5gb9ald45pssbp9gisildg20smgt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACBF62zVdl2YmA-02VSfRXpDrGwynUZQM',
    appId: '1:235787761557:web:82c7ac3285ce2e242de89c',
    messagingSenderId: '235787761557',
    projectId: 'demo1-47460',
    authDomain: 'demo1-47460.firebaseapp.com',
    storageBucket: 'demo1-47460.appspot.com',
    measurementId: 'G-94K28HL3J8',
  );
}